# Generated by Django 2.0.7 on 2018-07-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NowPlayingMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=1000)),
                ('movie_overview', models.CharField(max_length=1000)),
                ('movie_poster_url', models.CharField(max_length=1000)),
                ('movie_release_date', models.DateField()),
                ('slug', models.SlugField(max_length=500)),
                ('movie_db_id', models.IntegerField()),
                ('movie_trailer_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
